### ISSUE TITLE
[fa22] mentor06 (Sequences and Containers) 

### ISSUE THREAD

**Issue by adit-bala** [csmberkeley/csm-61a#138]
- Need to cover `shallow copying` vs `deep copying`
- Too many questions, `WWPD` took a long time
- Recursive environment diagram question is not that helpful
- better than `61b`'s worksheets

**Comment by gabeclasson** [comment]
Overall:
- Liked how it went over edge cases, problems are good
- liked how it covered list comprehensions
- Definitely a lot, we understand it is not meant to be completed but it still has an overwhelming effect
- We assume too little background knowledge of the students
- There were lots of WWPD questions so that section took some time.
- The ADT questions were good, more structure on the tree problems/direction on the tree questions would be nice. Would benice to have a soft ADT intro to trees. Tying ADT into trees would be better
- too many questions (sorry)

`comprehensions`:
- If you're going to include a question that includes the zip function, you should explain it in the text overview. 
- Parts c and d were difficult to explain.

`simple-modified-2`:
- If you're going to include a question that uses shallow and deep copying, you need to include it in the text overview. 

`reverse`:
-  Almost everyone skipped question 2 (recursive environment diagrams), didn't feel it was helpful/necessary
